#ifndef ESP32_C3_CANBUS_ARDUINO_TYPES_H
#define ESP32_C3_CANBUS_ARDUINO_TYPES_H

typedef enum can_speed_t {
    CAN_SPEED_25KBIT,
    CAN_SPEED_50KBIT,
    CAN_SPEED_100KBIT,
    CAN_SPEED_125KBIT,
    CAN_SPEED_250KBIT,
    CAN_SPEED_500KBIT,
    CAN_SPEED_800KBIT,
    CAN_SPEED_1MBIT,
    CAN_SPEED_MAX
} can_speed_t;

#endif //ESP32_C3_CANBUS_ARDUINO_TYPES_H
